### ISSUE TITLE
Master branch doesn't compile

### ISSUE THREAD

**Issue by etiennebouteille** [natar-io/PapARt#3]
Hi, 
I was not able to compile the library, it would seem that a dependecie is missing from clojar? 
Here's is the error I get : 
Could not resolve dependencies for project fr.inria:papart:jar:0.7-SNAPSHOT: Could not find artifact tech.lity.rea:SVGExtended:jar:3.2.1 in clojars.org (http://clojars.org/repo)

Hopefully it is not my mistake, as I am not used to doing this kind of things.
Cheers,
Etienne

**Comment by poqudrof** [comment]
Hello, 
It is not your problem at all. I did not push the `SVGExtended` library to maven central nor clojars... So it is my bad. 

I wrote compilation instructions here: https://github.com/poqudrof/PapARt/wiki/Compilation 

To handle your problem download and install SVGExtended.  https://github.com/poqudrof/SVGExtended

Tell me if this works good for you or if you have other troubles. This issue will be fixed for the next release of PapARt.

**Comment by etiennebouteille** [comment]
Installation successful! Thanks for your help.
I have to admit the process was much more complex than what I am used to with processing. (The fact that I am running windows had to do with it).
 Is there any particular reason you don't provide the library folder like most Processing libraries?

**Comment by poqudrof** [comment]
The svgextended library is quite new (22 days old) and I did not made a proper release in the papart repository. As you can see I just updated the wiki, and I work on other new unstable stuff. 

PapARt used to require a modified version of Processing, and it was distributed with all the dependencies, but restricted to some users because the code was proprietary. 

In the next release it will be a Processing library, or a collection of processing libraries available through the processing IDE.
