### ISSUE TITLE
PapARt flickering window if missing Processing draw function

### ISSUE THREAD

**Issue by vcz-fr** [natar-io/PapARt#6]
Hello,

When the draw() function is commented out or not present, the screen showing the camera output indefinitely flickers.
If this is wanted, would it be possible to raise an exception instead?

![image](https://cloud.githubusercontent.com/assets/9070606/21993918/87575058-dc1d-11e6-9bd9-6fecad88c1a8.png)

**Comment by poqudrof** [comment]
Hello, 
This is also known issue, and I do not know the cause... I did not investigate this, as the fix is just to have an empty draw() method. 
I guess it is feasible to check if the method is redefined with introspection: 

https://docs.oracle.com/javase/tutorial/reflect/member/methodInvocation.html
https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/Method.html

Get the class from which PapARt is loaded, and check is draw() is redefined and then throw an exception.

It put this in the "enhancement" which will be handled in the next effort of code.
